### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NubeBuster** [Nubebuster/Mining-Turtles#1]
# TODO
- [ ] add plugin tracking on mcstats
- [ ] check block data in PLACE
- [ ] play break particles
- [ ] add an ingame way for creating scripts. Books?
